/// Generated by Flutter GetX Starter on 2022-11-03 12:36

import 'package:chat_bubbles/bubbles/bubble_special_three.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:my_widgets/my_widgets.dart';
import 'package:my_widgets/widgets/dividers.dart';
import 'package:my_widgets/widgets/input.dart';
import 'package:my_widgets/widgets/loading.dart';

import '../../../utils/utils.dart';
import '../main.dart';
import 'chat_logic.dart';

class ChatView extends StatelessWidget {

  const ChatView({super.key});

  @override
  Widget build(BuildContext context) {
    deviceWidth = Get.width;
    deviceHeight = Get.height;
    return GetBuilder<ChatLogic>(
      init: ChatLogic(),
      builder: (logic) {
        return Material(
          child: logic.isLoading?const LoadingPro():Scaffold(
            appBar:AppBar(),
            body: Container(
              color: Clr.colorGreyBackground,
              child: Column(
                children: [
                  Expanded(
                    child: buildChatList(logic),
                  ),
                  const MyDivider(height: 5,),
                  Container(
                    decoration: pBoxDecoration(
                      color: logic.senderColor,
                      radius: 50,
                    ),
                    width: deviceWidth * 0.9,
                    margin: const EdgeInsets.symmetric(horizontal: Siz.standardPadding),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const MyVerticalDivider(),
                        Expanded(
                          child:TxtFormInput(
                            controller: logic.chatController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                            ),
                            hasLabel: false,
                            maxLines: 4,
                            minLines: 1,
                            hintText: 'type_here_to_send',
                            hintTextColor: Clr.colorBlack,
                          ),
                        ),

                        GestureDetector(
                          onTap: logic.onSendMessage,
                          child: Container(
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: Clr.colorPrimary,
                            ),
                            padding: const EdgeInsets.all(7),
                            child: const Icon(Icons.arrow_upward_outlined, color: Clr.colorWhite,),
                          ),
                        ),
                        const MyVerticalDivider(width: 4,),
                      ],
                    ),
                  ),
                  const MyDivider(),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget buildChatList(ChatLogic logic){
    return Obx(()=> ListView.separated(
        reverse: false,
        controller: logic.scrollController,
        itemBuilder: (ctx, i) {

          final msg = logic.list[i];
          bool isSender = msg.idFrom == userId;
          return Column(
            children: [
              BubbleSpecialThree(
                text: msg.content,
                color:
                isSender ? Clr.colorPrimary : logic.senderColor,
                tail: true,
                textStyle: TextStyle(
                  color: isSender ? Clr.colorWhite : Clr.colorBlack,
                  fontSize: 16,
                ),
                isSender: isSender,
              ),
            ],
          );
        },
        separatorBuilder: (ctx, i) {
          return const MyDivider();
        },
        itemCount:logic.list.length
    ));
  }
}
